name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to Raspberry Pi
      run: |
        rsync -avz --delete ./ pi@sjpret.co.za:/var/www/html/test

    - name: Run composer install
      run: |
        ssh pi@sjpret.co.za << 'EOF'
          cd /var/www/html/test
          composer install --no-dev --optimize-autoloader
        EOF
