name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.PI_PASSWORD }}" \
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ \
          ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }}:/var/www/html

      - name: Run Composer
        run: |
          sshpass -p "${{ secrets.PI_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} << 'EOF'
            cd /var/www/html
            composer install --no-dev --optimize-autoloader
            chmod -R 755 .
          EOF
